name: .NET CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: BookStore
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore BookStore.sln

      - name: Format code
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build BookStore.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BusinessLayer.Tests/BusinessLayer.Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx' 