name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore BookStore/BookStore.sln

      - name: Build
        run: dotnet build BookStore/BookStore.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BookStore/BookStore.sln --no-build --verbosity normal

      - name: Run (PresentationLayer)
        run: dotnet run --project BookStore/PresentationLayer/PresentationLayer.csproj
        env:
          ASPNETCORE_ENVIRONMENT: Development
        continue-on-error: true # Không fail job nếu run UI không thành công trên CI 